all:
  vars:
    node_version: "24"
    mongodb_version: "8.0"

  children:
    production:
      hosts:
        crowdtowers-prod:
          ansible_host: crowdtowers.wochenentwicklung.com
          ansible_user: deploy
          ansible_port: 22
      vars:
        app_name: crowdtowers-prod
        app_domain: crowdtowers.wochenentwicklung.com
        app_port: 3000
        app_path: /var/www/crowdtowers
        mongo_db_name: crowdtowers
        mongo_app_user: crowdtowers

    staging:
      hosts:
        crowdtowers-staging:
          ansible_host: crowdtowers.wochenentwicklung.com
          ansible_user: deploy
          ansible_port: 22
      vars:
        app_name: crowdtowers-staging
        app_domain: staging.crowdtowers.wochenentwicklung.com
        app_port: 3001
        app_path: /var/www/crowdtowers-staging
        mongo_db_name: crowdtowers-staging
        mongo_app_user: crowdtowers-staging
