all:
  hosts:
    crowdtowers:
      ansible_host: crowdtowers.wochenentwicklung.com
      ansible_user: deploy
      ansible_port: 22

  vars:
    app_name: crowdtowers
    app_domain: crowdtowers.wochenentwicklung.com
    app_port: 3000
    app_path: /var/www/crowdtowers
    node_version: "24"
    mongodb_version: "8.0"
